apiVersion: batch/v1
kind: Job
metadata:
  name: configure-vault
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: vault
      volumes:
#       # These are CA certs necessary to validate the certificate
#       # presented by remote cluster API endpoints. They will be
#       # mounted on /vault/certs.
#       - name: ca-certs
#         configMap:
#           name: ca-certs

#       # These are the credentials necessary for the vault to
#       # interact with our other clusters. They are mounted on
#       # /vault/creds.
#       - name: vault-credentials
#         secret:
#           secretName: vault-credentials

        # These are the vault configuration files from the config/
        # directoryin this repostiory. They will be mounted on
        # /vault/config.
        - name: vault-config
          configMap:
            name: vault-config

        # These are the certificates generated by the vault operator,
        # including the ca.crt necessary to validate vault's TLS
        # certificate. They will be mounted on /vault/tls.
        - name: vault-tls
          secret:
            secretName: vault-tls

        # We merge all the configuration files together into the
        # single configuration file expected by the bank-vaults cli.
        # This volume will be mounted on /merged.
        - name: merged-config
          emptyDir:
            medium: Memory
      initContainers:

        # The merge-config initContainer merges together all the YAML
        # files located in /vault/config, and places the output in
        # /merged/config.yaml.
        - name: merge-config
          image: docker.io/mikefarah/yq:4
          volumeMounts:
            - name: merged-config
              mountPath: /merged
            - name: vault-config
              mountPath: /vault/config
          command:
            # via https://stackoverflow.com/a/67036496
            - sh
            - -c
            - |
              yq eval-all '. as $item ireduce ({}; . *+ $item)' /vault/config/*.yaml > /merged/config.yaml

      containers:

        # The configure-vault uses the bank-vaults cli to read the
        # merged config from /merged/config.yaml, applies templates to
        # inject credentials and other files, and then applies the
        # configuration to the vault using the vault api.
        - name: configure-vault
          image: ghcr.io/bank-vaults/bank-vaults:v1.30.0
          volumeMounts:
            - name: merged-config
              mountPath: /merged
            - name: vault-tls
              mountPath: /vault/tls
#           - name: vault-credentials
#             mountPath: /vault/creds
#           - name: ca-certs
#             mountPath: /vault/certs
          env:
            - name: VAULT_ADDR
              value: https://vault:8200
            - name: VAULT_CACERT
              value: /vault/tls/ca.crt
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          workingDir: /vault
          args: [
            "configure",
            "--mode", "k8s",
            "--k8s-secret-namespace", "$(POD_NAMESPACE)",
            "--k8s-secret-name", "vault-unseal-keys",
            "--vault-config-file", "/merged/config.yaml",
            "--once",
            "--fatal"
          ]
