apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault
commonLabels:
  app: vault-config

resources:
- job.yaml

configMapGenerator:
  - name: vault-config
    options:
      disableNameSuffixHash: true
    files:
      - config/pki.yaml
