apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-secret
  namespace: default
spec:
  data:
  - remoteRef:
      key: secret/example-secret
      property: secret
    secretKey: secret
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secrets
  target:
    name: example-secret
