apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets
resources:
- sa/eso-vault-auth.yaml
- sa/vault-secret-reader.yaml
- secret/eso-vault-auth-token.yaml
- rbac/eso-tokenreview.yaml
- secretstore.yaml
- externalsecret.yaml
