apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-secrets
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes
          role: secret-reader
          serviceAccountRef:
            name: vault-secret-reader
            namespace: external-secrets
      path: secret
      server: http://vault.vault-test:8200
      version: v2
